Switched to use moustache templating engine for bash.
Added templates.

diff --git a/cite b/cite
--- a/cite
+++ b/cite
@@ -1,4 +1,5 @@
 #!/bin/bash
+
 # cite-stackoverflow
 #
 # Generate a citation for code used from stackoverflow.
@@ -40,45 +41,7 @@
 #
 # 3. Remove citations from a file.
 #
-# Dependencies: bash, curl, jq, and perl
-
-modified_template() {
-# Add prefix (usually whitespace), but don't add it if the line is blank.
-cat <<EOF | perl -pe "s/^(?=\s*\S)/$prefix/g;"
-/* Original code Copyright (c) $year_created $author_name[1]
-   Modified code Copyright (c) $year_modified $modifier_name[2]
-   Licensed under the CC-BY-SA 3.0[3]
-
-   Original code posted to this question[4] and answer[5] on
-   stackoverflow.com. This comment generated by cite-stackoverflow[6].
-
-   [1]: $author_link
-   [2]: $modifier_link
-   [3]: http://creativecommons.org/licenses/by-sa/3.0/
-   [4]: $question_link
-   [5]: $answer_link
-   [6]: $cite_stackoverflow_link
- */
-EOF
-}
-
-unmodified_template() {
-# Add prefix (usually whitespace), but don't add it if the line is blank.
-cat <<EOF | perl -pe "s/^(?=\s*\S)/$prefix/g;"
-/* Original code Copyright (c) $year_created $author_name[1]
-   Licensed under the CC-BY-SA 3.0[2]
-
-   Original code posted to this question[4] and answer[5] on
-   stackoverflow.com. This comment generated by cite-stackoverflow[6].
-
-   [1]: $author_link
-   [2]: http://creativecommons.org/licenses/by-sa/3.0/
-   [3]: $question_link
-   [4]: $answer_link
-   [5]: $cite_stackoverflow_link
- */
-EOF
-}
+# Dependencies: bash, curl, jq, mo, and perl
 
 # /*
 #    Original code Copyright (c) 2011 cdiggins[1]
@@ -120,9 +83,29 @@ cite_stackoverflow_link="https://gist.github.com/shanecelis/ea2b472af1adfcb995d8
 client_id="10102";
 client_key="nvTB2XGxj5eWuyeMCmJTJA((";
 
+source "$HOME/bin/mo";
+template_dir="$HOME/Projects/cite-stackoverflow/templates/";
+template="modified";
+year_modified=2016
+modifier_name="Shane Celis"
+modifier_link="https://twitter.com/shanecelis"
+license_name="CC-BY-SA 3.0"
+license_link="http://creativecommons.org/licenses/by-sa/3.0/"
+
+inline_link_count=0
+inline_link() {
+    inline_link_count=$((inline_link_count + 1));
+    echo $inline_link_count;
+}
+ref_link_count=0
+ref_link() {
+    ref_link_count=$((ref_link_count + 1));
+    echo $ref_link_count;
+}
+
 usage() {
-    echo "usage: cite [-hvCimM] [-n modifier-name] [-l modifier-link] [-y year-modified] [-p prefix]" >&2;
-    echo "                      [-c config]" >&2;
+    echo "usage: cite [-hvCimMT] [-n modifier-name] [-l modifier-link] [-y year-modified] [-p prefix]" >&2;
+    echo "                      [-c config] [-t template]" >&2;
     echo "                      <-u question-or-answer-url| -q question-id | -a answer-id>" >&2;
     echo " -h      Show usage." >&2;
     echo " -v      Be verbose." >&2;
@@ -133,6 +116,7 @@ usage() {
     echo " -n      Who modified this code?" >&2;
     echo " -l      Where can I find them?" >&2;
     echo " -y      What year was it modified?" >&2;
+    echo " -T      List templates" >&2;
     echo " -p      Prefix each line of template with 'prefix'; used mainly for alignment." >&2;
     echo " -i      Interactive. Ask user if not specified." >&2;
 }
@@ -183,7 +167,7 @@ display_answer_warning() {
     no_answer_path=/tmp/cite-stackoverflow/no_answers.$pid;
     if [ -f "$no_answer_path" ]; then
         if [ $verbose -eq 1 ]; then
-            echo "warning: Answer not specified for following questions; assuming first answer was used: $(cat $no_answer_path | sort | uniq | tr '\n' ',')" >&2;
+            echo "warning: Answer not specified for following questions: $(cat $no_answer_path | sort | uniq | tr '\n' ',')" >&2;
         else
             count=$(cat "$no_answer_path" | sort | uniq | wc -l | xargs); # xargs is working like trim
             echo "warning: Answer not specified for $count questions; assuming first answer was used." >&2;
@@ -204,7 +188,8 @@ if [ -z "$ROOT_PID" ]; then
 fi
 # trap 'rc=$?; echo "ERR at line ${LINENO} (rc: $rc)"; exit $rc' ERR
 # trap 'rc=$?; echo "EXIT (rc: $rc)"; exit $rc' EXIT
-set -ueE -o pipefail;
+#set -ueE -o pipefail;
+set -eE -o pipefail;
 trap '[ $? -ne 0 ] && echo "error: internal script error at line ${LINENO}."' ERR
 dryrun=0;
 verbose=0;
@@ -212,12 +197,15 @@ verbose=0;
 use_cache=1;
 interactive=0;
 modified=2;                     # 2 means it's not clear which
+# modifier_name="";
+# modifier_link="";
+# year_modified="";
 prefix="";
 question_id="";
 answer_id="";
 url="";
 config_file="";
-while getopts "in:ChvmMq:a:l:y:u:" arg; do
+while getopts "Tin:Chvmp:Mq:a:l:y:u:t:" arg; do
     case "$arg" in
         h) usage;
            exit 0;;
@@ -241,6 +229,10 @@ while getopts "in:ChvmMq:a:l:y:u:" arg; do
         q) question_id="$OPTARG";;
         a) answer_id="$OPTARG";;
         u) url="$OPTARG";;
+        t) template="$OPTARG";;
+        T) echo "Templates available from $template_dir: ";
+           (cd $template_dir; echo *);
+           exit 0;;
         *) usage;
            exit 2;;
     esac
@@ -283,16 +275,23 @@ if [ -z "$answer_id" ]; then
         declare -a answer_options=()
         while IFS= read -r line; do
             answer_options+=( "$line" )
-        done < <(printf "%-20s %5s %s\n" "Name" "Score" "Answer ID"; echo "$question_answers_json" | jq -r '.items[] | .owner.display_name, .score, .answer_id' | perl -e 'while (<>) { $n = $_; $s = <>; $a = <>; chomp($n); printf("%-20s %5d %d\n", $n, $s, $a); }');
+        done < <( echo "$question_answers_json" | jq -r '.items[] | .owner.display_name, .score, .answer_id' | perl -e 'while (<>) { $n = $_; $s = <>; $a = <>; chomp($n); printf("%-20s %5d %d\n", $n, $s, $a); }');
+        answer_options+=( "$(echo "No answer; question contains the code.")" );
+        printf "    %-20s %5s %s\n" "Name" "Score" "Answer ID";
         select value in "${answer_options[@]}"; do
             index="$REPLY";
-            if [ "$index" -ne 1 ]; then
-                answer_id="$(echo "$question_answers_json" | jq -r ".items[$((index - 2))].answer_id")";
+            if [ "$index" -eq "${#answer_options[@]}" ]; then
+                # No answer used.
+                answer_id="NONE";
+                break;
+            elif [ "$index" -ne 1 ]; then
+                answer_id="$(echo "$question_answers_json" | jq -r ".items[$((index - 1))].answer_id")";
                 break;
             fi
         done
     else
-        answer_id="$(echo "$question_answers_json" | jq -r '.items[0].answer_id')"
+        #answer_id="$(echo "$question_answers_json" | jq -r '.items[0].answer_id')"
+        answer_id="NONE";
         no_answer_path=/tmp/cite-stackoverflow/no_answers.$ROOT_PID;
         echo $question_id >> "$no_answer_path";
         #echo "warning: Answer not specified for question $question_id; assuming first answer (${answer_id}) was used." >&2;
@@ -306,16 +305,28 @@ if [ -z "$answer_id" ]; then
     echo "error: no answer ID determined." >&2;
     exit 3;
 fi
-answer_json="$(stackexchange-query 'answers/'$answer_id)"
-author_link="$(echo "$answer_json" | jq -r '.items[0].owner.link')"
-answer_link="https://stackoverflow.com/a/$answer_id";
-author_name="$(echo "$answer_json" | jq -r '.items[0].owner.display_name')"
-question_id="$(echo "$answer_json" | jq -r '.items[0].question_id')"
-# answer_id="$(echo "$answer_json" | jq -r '.items[0].answer_id')"
-if ! year_created="$(date -r $(echo "$answer_json" | jq -r '.items[0].creation_date') '+%Y')"; then
-    echo "error: not able to parse date from the following JSON." >&2;
-    echo "$answer_json" >&2;
-    exit 1;
+
+if [ "$answer_id" != "NONE" ]; then
+    answer_json="$(stackexchange-query 'answers/'$answer_id)"
+    author_link="$(echo "$answer_json" | jq -r '.items[0].owner.link')"
+    answer_link="https://stackoverflow.com/a/$answer_id";
+    author_name="$(echo "$answer_json" | jq -r '.items[0].owner.display_name')"
+    question_id="$(echo "$answer_json" | jq -r '.items[0].question_id')"
+    # answer_id="$(echo "$answer_json" | jq -r '.items[0].answer_id')"
+    if ! year_created="$(date -r $(echo "$answer_json" | jq -r '.items[0].creation_date') '+%Y')"; then
+        echo "error: not able to parse date from the following JSON." >&2;
+        echo "$answer_json" >&2;
+        exit 1;
+    fi
+else
+    author_name="$(echo "$question_json" | jq -r '.items[0].owner.display_name')"
+    author_link="$(echo "$question_json" | jq -r '.items[0].owner.link')"
+    if ! year_created="$(date -r $(echo "$question_json" | jq -r '.items[0].creation_date') '+%Y')"; then
+        echo "error: not able to parse date from the following JSON." >&2;
+        echo "$question_json" >&2;
+        exit 8;
+    fi
+
 fi
 
 if [ $modified -eq 2 ]; then
@@ -348,7 +359,7 @@ if [ $modified -eq 1 ]; then
     fi
     if [ -z "$modifier_link" ]; then
         if [ $interactive -eq 1 ]; then
-            # Ask for modifier's name.
+            # Ask for modifier's link.
             read -p "Link or email to modifier: " modifier_link
             # Might be nice to show the git contributor emails:
             # git log --pretty="%ae" | sort | uniq
@@ -358,9 +369,22 @@ if [ $modified -eq 1 ]; then
             exit 6;
         fi
     fi
-    modified_template;
+    if [ -z "$year_modified" ]; then
+        if [ $interactive -eq 1 ]; then
+            read -p "Year modified: " year_modified
+        else
+            echo "error: no year_modified given. Either use -y or -i." >&2;
+            usage;
+            exit 6;
+        fi
+    fi
 else
-    unmodified_template;
+    modifier_name="";
 fi
-
-
+# Add prefix (usually whitespace), but don't add it if the line is blank.
+#prefix_length=$(echo -n "$prefix" | wc -c)
+# Folding had a couple issues:
+# 1. It'd fold the URLs.
+# 2. It'd fold without adding enough spaces to have the text flush.
+#mo "$template" | fold -sw $((80 - prefix_length)) | perl -pe "s/^(?=\s*\S)/$prefix/g;";
+mo "$template" | perl -pe "s/^(?=\s*\S)/$prefix/g;";
