cite is working now. cite-inline needs work.

diff --git a/cite b/cite
--- a/cite
+++ b/cite
@@ -85,7 +85,7 @@ client_key="nvTB2XGxj5eWuyeMCmJTJA((";
 
 source "$HOME/bin/mo";
 template_dir="$HOME/Projects/cite-stackoverflow/templates/";
-template="modified";
+template="stackoverflow";
 year_modified=2016
 modifier_name="Shane Celis"
 modifier_link="https://twitter.com/shanecelis"
@@ -105,7 +105,7 @@ ref_link() {
 
 usage() {
     echo "usage: cite [-hvCimMT] [-n modifier-name] [-l modifier-link] [-y year-modified] [-p prefix]" >&2;
-    echo "                      [-c config] [-t template]" >&2;
+    echo "                      [-c config] [-t template] [-W pid]" >&2;
     echo "                      <-u question-or-answer-url| -q question-id | -a answer-id>" >&2;
     echo " -h      Show usage." >&2;
     echo " -v      Be verbose." >&2;
@@ -159,7 +159,9 @@ display_cache_warning() {
             echo "warning: Used cache for $count stackexchange API requests." >&2;
         fi
         rm "$keys_used_path";
+        return 1;
     fi
+    return 0;
 }
 
 display_answer_warning() {
@@ -170,10 +172,42 @@ display_answer_warning() {
             echo "warning: Answer not specified for following questions: $(cat $no_answer_path | sort | uniq | tr '\n' ',')" >&2;
         else
             count=$(cat "$no_answer_path" | sort | uniq | wc -l | xargs); # xargs is working like trim
-            echo "warning: Answer not specified for $count questions; assuming first answer was used." >&2;
+            echo "warning: Answer not specified for $count questions." >&2;
         fi
         rm "$no_answer_path";
+        return 1;
     fi
+    return 0;
+}
+
+display_modified_warning() {
+    pid=$1;
+    modified_path=/tmp/cite-stackoverflow/modified.$pid;
+    if [ -f "$modified_path" ]; then
+        if [ $verbose -eq 1 ]; then
+            echo "warning: not specified whether code was modified for following questions: $(cat $modified_path | sort | uniq | tr '\n' ',')" >&2;
+        else
+            count=$(cat "$modified_path" | sort | uniq | wc -l | xargs); # xargs is working like trim
+            echo "warning: Not specified whether code was modified for $count cases." >&2;
+        fi
+        rm "$modified_path";
+        return 1;
+    fi
+    return 0;
+}
+
+display_warnings() {
+    err=0;
+    trap - ERR
+    set +e;
+    display_answer_warning $1;
+    let "err|=$?"
+    display_cache_warning $1;
+    let "err|=$?"
+    display_modified_warning $1;
+    let "err|=$?"
+    set -e;
+    return $err;
 }
 
 stackexchange-query() {
@@ -182,9 +216,10 @@ stackexchange-query() {
     # echo "memo $memoize_key for query $query args $*" >&2;
     memoize "$memoize_key" curl -s 'https://api.stackexchange.com/2.2/'"$query"'?order=desc&sort=votes&site=stackoverflow&key='"$client_key" | gzcat
 }
+
 if [ -z "$ROOT_PID" ]; then
     export ROOT_PID=$$;
-    trap "display_answer_warning $ROOT_PID; display_cache_warning $ROOT_PID" EXIT
+    trap "display_warnings $ROOT_PID" EXIT
 fi
 # trap 'rc=$?; echo "ERR at line ${LINENO} (rc: $rc)"; exit $rc' ERR
 # trap 'rc=$?; echo "EXIT (rc: $rc)"; exit $rc' EXIT
@@ -205,7 +240,7 @@ question_id="";
 answer_id="";
 url="";
 config_file="";
-while getopts "Tin:Chvmp:Mq:a:l:y:u:t:" arg; do
+while getopts "W:Tin:Chvmp:Mq:a:l:y:u:t:" arg; do
     case "$arg" in
         h) usage;
            exit 0;;
@@ -230,6 +265,8 @@ while getopts "Tin:Chvmp:Mq:a:l:y:u:t:" arg; do
         a) answer_id="$OPTARG";;
         u) url="$OPTARG";;
         t) template="$OPTARG";;
+        W) display_warnings $OPTARG;
+           exit $?;;
         T) echo "Templates available from $template_dir: ";
            (cd $template_dir; echo *);
            exit 0;;
@@ -339,8 +376,10 @@ if [ $modified -eq 2 ]; then
             modified=0;
         fi
     else
-        echo "warning: assuming the code has been modified." >&2;
-        modified=1;
+        # echo "warning: assuming the code has not been modified." >&2;
+        modified_path=/tmp/cite-stackoverflow/modified.$ROOT_PID;
+        echo $question_id >> "$modified_path";
+        modified=0;
     fi
 fi
 
@@ -387,4 +426,9 @@ fi
 # 1. It'd fold the URLs.
 # 2. It'd fold without adding enough spaces to have the text flush.
 #mo "$template" | fold -sw $((80 - prefix_length)) | perl -pe "s/^(?=\s*\S)/$prefix/g;";
-mo "$template" | perl -pe "s/^(?=\s*\S)/$prefix/g;";
+if [ -f "$template_dir/$template" ]; then
+    mo "$template_dir/$template" | perl -pe "s/^(?=\s*\S)/$prefix/g;";
+else
+    echo "error: no template $template_dir/$template" >&2;
+    exit 9;
+fi
